"""initial schema

Revision ID: 3253b1fbe58d
Revises: 
Create Date: 2026-08-03 15:37:14.678931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3253b1fbe58d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('legal_name', sa.String(length=512), nullable=True),
    sa.Column('website_domain', sa.String(length=255), nullable=True),
    sa.Column('cin', sa.String(length=32), nullable=True),
    sa.Column('llpin', sa.String(length=32), nullable=True),
    sa.Column('gstin', sa.String(length=32), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('company_type', sa.String(length=64), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('operating_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('sub_industry', sa.String(length=128), nullable=True),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_model', sa.String(length=16), nullable=True),
    sa.Column('company_category', sa.String(length=32), nullable=True),
    sa.Column('export_status', sa.Boolean(), nullable=True),
    sa.Column('markets_served', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_range_min', sa.Integer(), nullable=True),
    sa.Column('employee_range_max', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_range_min_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_range_max_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_year', sa.Integer(), nullable=True),
    sa.Column('growth_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public_phone', sa.String(length=32), nullable=True),
    sa.Column('public_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_annual_revenue_inr'), 'companies', ['annual_revenue_inr'], unique=False)
    op.create_index(op.f('ix_companies_cin'), 'companies', ['cin'], unique=True)
    op.create_index(op.f('ix_companies_city'), 'companies', ['city'], unique=False)
    op.create_index(op.f('ix_companies_company_category'), 'companies', ['company_category'], unique=False)
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index('ix_companies_employee_range', 'companies', ['employee_range_min', 'employee_range_max'], unique=False)
    op.create_index(op.f('ix_companies_employee_range_max'), 'companies', ['employee_range_max'], unique=False)
    op.create_index(op.f('ix_companies_employee_range_min'), 'companies', ['employee_range_min'], unique=False)
    op.create_index(op.f('ix_companies_gstin'), 'companies', ['gstin'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_llpin'), 'companies', ['llpin'], unique=True)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_companies_postal_code'), 'companies', ['postal_code'], unique=False)
    op.create_index(op.f('ix_companies_revenue_year'), 'companies', ['revenue_year'], unique=False)
    op.create_index(op.f('ix_companies_state'), 'companies', ['state'], unique=False)
    op.create_index('ix_companies_state_city_industry', 'companies', ['state', 'city', 'industry'], unique=False)
    op.create_index(op.f('ix_companies_sub_industry'), 'companies', ['sub_industry'], unique=False)
    op.create_index(op.f('ix_companies_website_domain'), 'companies', ['website_domain'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('collection_enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('robots_notes', sa.Text(), nullable=True),
    sa.Column('license_notes', sa.Text(), nullable=True),
    sa.Column('retention_notes', sa.Text(), nullable=True),
    sa.Column('reliability_weight', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('company_aliases',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('normalized_alias', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_index('ix_company_aliases_company_normalized', 'company_aliases', ['company_id', 'normalized_alias'], unique=True)
    op.create_index(op.f('ix_company_aliases_normalized_alias'), 'company_aliases', ['normalized_alias'], unique=False)
    op.create_table('evidence',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('range_min', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('range_max', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('financial_year', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('verification_type', sa.String(length=16), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'field', name='uq_evidence_company_field')
    )
    op.create_index('ix_evidence_company_field', 'evidence', ['company_id', 'field'], unique=False)
    op.create_index(op.f('ix_evidence_company_id'), 'evidence', ['company_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_discovered', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'idempotency_key', name='uq_ingestion_job_source_idempotency')
    )
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('raw_observations',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('verification_type', sa.String(length=16), nullable=False),
    sa.Column('collector_version', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_observations_company_field', 'raw_observations', ['company_id', 'field'], unique=False)
    op.create_index(op.f('ix_raw_observations_company_id'), 'raw_observations', ['company_id'], unique=False)
    op.create_index(op.f('ix_raw_observations_field'), 'raw_observations', ['field'], unique=False)
    op.create_index('ix_raw_observations_source_collected', 'raw_observations', ['source_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_raw_observations_source_id'), 'raw_observations', ['source_id'], unique=False)
    op.create_table('entity_match_candidates',
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('candidate_company_id', sa.UUID(), nullable=True),
    sa.Column('incoming_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('matched_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['raw_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_match_candidates_candidate_company_id'), 'entity_match_candidates', ['candidate_company_id'], unique=False)
    op.create_index(op.f('ix_entity_match_candidates_observation_id'), 'entity_match_candidates', ['observation_id'], unique=False)
    op.create_index(op.f('ix_entity_match_candidates_status'), 'entity_match_candidates', ['status'], unique=False)
    op.create_table('evidence_observations',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['raw_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', 'observation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_observations')
    op.drop_index(op.f('ix_entity_match_candidates_status'), table_name='entity_match_candidates')
    op.drop_index(op.f('ix_entity_match_candidates_observation_id'), table_name='entity_match_candidates')
    op.drop_index(op.f('ix_entity_match_candidates_candidate_company_id'), table_name='entity_match_candidates')
    op.drop_table('entity_match_candidates')
    op.drop_index(op.f('ix_raw_observations_source_id'), table_name='raw_observations')
    op.drop_index('ix_raw_observations_source_collected', table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_field'), table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_company_id'), table_name='raw_observations')
    op.drop_index('ix_raw_observations_company_field', table_name='raw_observations')
    op.drop_table('raw_observations')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_evidence_company_id'), table_name='evidence')
    op.drop_index('ix_evidence_company_field', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_company_aliases_normalized_alias'), table_name='company_aliases')
    op.drop_index('ix_company_aliases_company_normalized', table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_companies_website_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_sub_industry'), table_name='companies')
    op.drop_index('ix_companies_state_city_industry', table_name='companies')
    op.drop_index(op.f('ix_companies_state'), table_name='companies')
    op.drop_index(op.f('ix_companies_revenue_year'), table_name='companies')
    op.drop_index(op.f('ix_companies_postal_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_llpin'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_gstin'), table_name='companies')
    op.drop_index(op.f('ix_companies_employee_range_min'), table_name='companies')
    op.drop_index(op.f('ix_companies_employee_range_max'), table_name='companies')
    op.drop_index('ix_companies_employee_range', table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_category'), table_name='companies')
    op.drop_index(op.f('ix_companies_city'), table_name='companies')
    op.drop_index(op.f('ix_companies_cin'), table_name='companies')
    op.drop_index(op.f('ix_companies_annual_revenue_inr'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
