"""gst registrations and financial year history

Revision ID: 4920c24524c9
Revises: 79225fb5bcff
Create Date: 2026-08-04 01:49:59.101716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4920c24524c9'
down_revision: Union[str, Sequence[str], None] = '79225fb5bcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financials',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('annual_revenue_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_range_min_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_range_max_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('authorized_capital_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('paidup_capital_inr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('verification_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'financial_year', name='uq_company_financials_company_year')
    )
    op.create_index(op.f('ix_company_financials_company_id'), 'company_financials', ['company_id'], unique=False)
    op.create_table('company_gst_registrations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('registered_state', sa.String(length=128), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('cancellation_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_gst_registrations_company_id'), 'company_gst_registrations', ['company_id'], unique=False)
    op.create_index('ix_company_gst_registrations_company_primary', 'company_gst_registrations', ['company_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_company_gst_registrations_gstin'), 'company_gst_registrations', ['gstin'], unique=True)
    # NOTE: autogenerate also proposed dropping the pg_trgm GIN indexes from
    # 79225fb5bcff (ix_companies_normalized_name_trgm, ix_companies_website_domain_trgm,
    # ix_company_aliases_normalized_alias_trgm). Those are created with raw `op.execute()`
    # SQL, not declared on the SQLAlchemy models, so autogenerate's model-vs-DB diff
    # doesn't see them and treats them as extraneous. Deliberately not dropping them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_gst_registrations_gstin'), table_name='company_gst_registrations')
    op.drop_index('ix_company_gst_registrations_company_primary', table_name='company_gst_registrations')
    op.drop_index(op.f('ix_company_gst_registrations_company_id'), table_name='company_gst_registrations')
    op.drop_table('company_gst_registrations')
    op.drop_index(op.f('ix_company_financials_company_id'), table_name='company_financials')
    op.drop_table('company_financials')
    # ### end Alembic commands ###
