"""saved searches

Revision ID: 4ffd7972b684
Revises: 5c66876cc0f9
Create Date: 2026-08-12 13:13:44.715519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ffd7972b684'
down_revision: Union[str, Sequence[str], None] = '5c66876cc0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: autogenerate also proposed dropping the pg_trgm GIN indexes from
    79225fb5bcff (ix_companies_normalized_name_trgm, ix_companies_website_domain_trgm,
    ix_company_aliases_normalized_alias_trgm). Those are created with raw
    `op.execute()` SQL, not declared on the SQLAlchemy models, so autogenerate's
    model-vs-DB diff doesn't see them and treats them as extraneous -- same false
    positive noted in 4920c24524c9 and 5c66876cc0f9. Deliberately not dropping them here.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('country_scope', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('source_scope', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('filter_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_searches_created_by', 'saved_searches', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_searches_created_by', table_name='saved_searches')
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
