"""generic source metadata and company country code

Revision ID: 5c66876cc0f9
Revises: 4920c24524c9
Create Date: 2026-08-12 11:51:14.244937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c66876cc0f9'
down_revision: Union[str, Sequence[str], None] = '4920c24524c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: autogenerate also proposed dropping the pg_trgm GIN indexes from
    79225fb5bcff (ix_companies_normalized_name_trgm, ix_companies_website_domain_trgm,
    ix_company_aliases_normalized_alias_trgm). Those are created with raw
    `op.execute()` SQL, not declared on the SQLAlchemy models, so autogenerate's
    model-vs-DB diff doesn't see them and treats them as extraneous -- same false
    positive noted in 4920c24524c9. Deliberately not dropping them here.

    server_default is set on every new NOT NULL column so this migration is
    safe to run against tables that already have rows (both `sources` and
    `companies` do, once any adapter has run) -- these are the exact values
    Source.access_method/compliance_status/countries default to at the
    Python/ORM level (see app/models/source.py), just also enforced at the
    DB level for any row inserted outside the ORM.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_companies_country_code'), 'companies', ['country_code'], unique=False)
    op.add_column('sources', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column(
        'sources',
        sa.Column(
            'countries', postgresql.ARRAY(sa.String(length=2)), nullable=False, server_default=sa.text("'{}'")
        ),
    )
    op.add_column(
        'sources', sa.Column('access_method', sa.String(length=32), nullable=False, server_default='unknown')
    )
    op.add_column(
        'sources',
        sa.Column('compliance_status', sa.String(length=32), nullable=False, server_default='under_review'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'compliance_status')
    op.drop_column('sources', 'access_method')
    op.drop_column('sources', 'countries')
    op.drop_column('sources', 'display_name')
    op.drop_index(op.f('ix_companies_country_code'), table_name='companies')
    op.drop_column('companies', 'country_code')
    # ### end Alembic commands ###
